-- AlterTable
ALTER TABLE "PiggyBank" ALTER COLUMN "balance" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Stock" ALTER COLUMN "average_price" SET DEFAULT 0,
ALTER COLUMN "average_price" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "last_action_price" SET DEFAULT 0,
ALTER COLUMN "last_action_price" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "pnl" SET DEFAULT 0,
ALTER COLUMN "pnl" SET DATA TYPE DOUBLE PRECISION;
